# Use the official Python image.
FROM python:3.10

# Set the working directory in the container.
WORKDIR /app

# Copy the requirements file and install dependencies.
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copy the rest of the application code.
COPY . .

# Expose the port the app runs on.
EXPOSE 5000

# Define environment variable.
ENV FLASK_APP=app.py

# Run the application.
CMD ["flask", "run", "--host=0.0.0.0"]
